### ISSUE TITLE
Index field mapping for static fields and dynamic fields  for elastic search

### ISSUE THREAD

**Issue by bvnagaraju** [knowbase/Knowbase#9]
Hi ,

we have a scenario where we know set of fields that we need at the time of index creation .This we know how do create field mapping at time of index creation .

But ,
we have other scenario where users can create custom fields after index creation .

Not sure how to do it .? If you can help with us sample code , it will be big help .

Also interested knowing thoughts on document schema this case

**Comment by jeroenvisser101** [comment]
Hi there,

I believe this has nothing to do with Knowbase, as Knowbase is just an application *using* elasticsearch, not elasticsearch itself. Please move the question to a more relevant site like stackoverflow.com or a mailing group.
